# Generated by Django 5.2.2 on 2025-06-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cutoffrecord_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='timing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='type',
            field=models.CharField(blank=True, choices=[('Pickup', 'Pickup'), ('Drop', 'Drop')], max_length=10, null=True),
        ),
    ]
