# Generated by Django 5.2.2 on 2025-06-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_schedule_timing_schedule_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cutoffrecord',
            options={'ordering': ['-cutoff_date']},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date', 'employee__employee_id', 'type']},
        ),
        migrations.AddField(
            model_name='cutoffrecord',
            name='date_range_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cutoffrecord',
            name='date_range_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cutoffrecord',
            name='total_schedules',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('employee', 'date', 'type')},
        ),
    ]
